const INTRODUZIONE_DATA = [
    { type: "titolo", testo: "Introduzione: L'Eco degli Sguardi" },
    { type: "testo", paragrafo: "Ci sono luoghi che ci chiamano da lontano, prima ancora di averli visti. Istanbul e Tangeri, per me sono sempre state loro \"i luoghi\", diverse eppure in un certo senso uguali." },
    { type: "testo", paragrafo: "Per lungo tempo, istintivamente, ho percepito tra loro un \"gemellaggio\", un legame segreto che non riuscivo a spiegare. Entrambe città di porto, entrambe crocevia, eppure così differenti. Istanbul, ai miei occhi, \"affascinante, caotica, pulsante\"; Tangeri \"razionale, ordinata, schematica\"." },
    { type: "testo", paragrafo: "Questo libro nasce dal tentativo di capire la natura di quel legame e finalmente, dopo un'attenta riflessione, ho trovato la risposta: Istanbul e Tangeri \"Le Sorelle degli Stretti\"." },
    { type: "testo", paragrafo: "Non gemelle identiche, ma sorelle geograficamente nate da uno stesso destino, entrambe sono poste a guardia di un \"cancello\" d'acqua: Istanbul veglia sul Bosforo, il ponte tra Asia ed Europa; Tangeri vigila su Gibilterra, il confine tra Africa ed Europa." },
    { type: "testo", paragrafo: "Questo destino ha forgiato le loro anime, ed è attraverso i miei \"sguardi\" immortalati dalle foto, che ho cercato di catturare la loro essenza." },
    { type: "testo", paragrafo: "Sguardi fatti \"d'Acqua e Pietra\": l'acqua eterna e mobile dei loro stretti, che porta vita e caos; la pietra delle loro storie millenarie che passano dai ciottoli dei vicoli ai marmi dei palazzi, dalle antiche mura ai moderni grattacieli." },
    { type: "testo", paragrafo: "Dal confronto prendono vita le differenze e le similitudini. Istanbul \"l'Anima Multipla\". Non è una città, è un universo, un mosaico di anime, ottomana, bizantina, genovese, greca, ebraica, che si scontrano e si sovrappongono convivendo in un caos sublime, il cui cuore pulsante è il Corno d'Oro. Istanbul non ha un'anima sola; è una moltitudine di anime." },
    { type: "testo", paragrafo: "Tangeri \"la Sentinella\". La sua è un'anima unica, proiettata verso l'esterno. È il confine, il faro, l'Africa che guarda l'Europa. La sua identità, come recita un suo vecchio poster, è quella di essere \"Entre les duex\", tra i due mondi. È orgoglosa, definita, la sua bellezza è nel dialogo costante con \"l'altro\" che le sta di fronte." },
    { type: "testo", paragrafo: "Le fotografie che seguono sono il mio diario di viaggio personale alla scoperta di queste due anime: lo \"sguardo\" fiero della Sentinella e gli \"sguardi\" infiniti dell'Anima Multipla." }
];